# -*- coding: utf-8 -*-
"""hw01-tolstoy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrfn5htAmINYXKgNhEGTzxPKDmVrsgIA

## Assignment: write a script that calculates the number of unique words in Tolstoy’s War and Peace

### Step 1: Import Modules
"""

from urllib import request
import re

"""### Step 2: Read Into Variable From URL
  - open the url and decode each line into a list
"""

url = 'https://www.gutenberg.org/files/2600/2600-0.txt'
file = request.urlopen(url)

text_list = [line.decode('utf-8') for line in file]

"""### Step 3: Create Cleaning Function
  - Turn list into string
  - split string into list of words
  - make everything lowercase
  - remove special characters
  - remove numbers
  - convert all spaces to single space
  - remove empty lines
"""

def clean(text_list):
  # flatten the list
  joined = ' '.join(text_list)

  # split by word
  text = joined.split(' ')

  # make everything lowercase
  lowercase = [i.lower() for i in text]

  # remove special characters
  symbol = [re.sub('\W'," ", line) for line in lowercase]

  # remove numbers
  numbers = [re.sub('\d+'," ", line) for line in symbol]

  # make spaces single space
  whitespace = [re.sub('\s+',"", line) for line in numbers]

  # remove empty lines if there are any
  empty = [line for line in whitespace if line]
  return empty

"""### Step 4: Send Text Through Cleaning Function
  - run function with text_list as input
  - convert list to set because set only keeps one instance of each item
  - find length of set
"""

# store output of function as a variable
cleaned = clean(text_list)

# convert list to set because sets only contain unique values
unique = set(cleaned)

# length of a set is the number of unique words
print("There are " + str(len(unique)) + " unique words in this text.")

"""### Furthur efforts
If we're looking only for the counts of the words in the actual book and not the editors notes or anything else, must first remove those. SO:
- Remove everything up to the beginning of the first chapter
  - title page, copyright info, table of contents, end comments, etc
  - Book 1 starts at line 827 and the content ends 352 lines from the end where legal notice begins
    - trial and error. Just sliced until I found the right start/stop
"""

# save only the items between these indices
just_text = text_list[827:-352]

clean_text = clean(just_text)

new_unique = set(clean_text)
print("There are " + str(len(new_unique)) + " unique words after removing publishing additions.")

"""### Not a big difference but there is a difference"""